version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLITE_FILE_NAME=db.db
    command: ["uvicorn", "project_management.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
